import React, { useState } from 'react';
import { OutfitOption } from '../types';
import { 
  Wand2, Share2, Bookmark, X, Sparkles,
  Briefcase, Sun, Moon, Activity, Gem, Feather 
} from 'lucide-react';

interface OutfitCardProps {
  outfit: OutfitOption;
  onSelect: (outfit: OutfitOption) => void;
}

const OutfitCard: React.FC<OutfitCardProps> = ({ outfit, onSelect }) => {
  const [showSaveDialog, setShowSaveDialog] = useState(false);
  const [customName, setCustomName] = useState('');
  const [customNotes, setCustomNotes] = useState('');

  const getStyleIcon = (style: string) => {
    const props = { className: "w-12 h-12 text-zinc-500/80 group-hover:text-zinc-400 transition-colors duration-500" };
    switch (style) {
        case 'Business': return <Briefcase {...props} />;
        case 'Casual': return <Sun {...props} />;
        case 'Night Out': return <Moon {...props} />;
        case 'Athleisure': return <Activity {...props} />;
        case 'Formal': return <Gem {...props} />;
        case 'Bohemian': return <Feather {...props} />;
        default: return <Sparkles {...props} />;
    }
  };

  const handleShare = async (e: React.MouseEvent) => {
    e.stopPropagation();
    if (!outfit.imageUrl) return;

    try {
      const response = await fetch(outfit.imageUrl);
      const blob = await response.blob();
      const file = new File([blob], `style-forge-${outfit.style.toLowerCase()}.png`, { type: 'image/png' });

      // Check if Web Share API is supported and can handle files
      if (navigator.canShare && navigator.canShare({ files: [file] })) {
        await navigator.share({
          title: `Style Forge - ${outfit.style} Look`,
          text: `Check out this ${outfit.style} outfit idea generated by Style Forge!\n\n"${outfit.description}"`,
          files: [file],
        });
      } else {
        // Fallback: Try to copy to clipboard
        try {
            await navigator.clipboard.write([
                new ClipboardItem({
                    [blob.type]: blob
                })
            ]);
            alert("Image copied to clipboard!");
        } catch (clipboardError) {
            console.error("Clipboard write failed", clipboardError);
            alert("Sharing is not supported on this device. You can download the image using the Edit view instead.");
        }
      }
    } catch (error) {
      console.error('Error sharing:', error);
      alert("Failed to prepare image for sharing.");
    }
  };

  const handleSaveClick = (e: React.MouseEvent) => {
    e.stopPropagation();
    if (!outfit.imageUrl) return;
    
    setCustomName(`${outfit.style} Look`);
    setCustomNotes(outfit.description);
    setShowSaveDialog(true);
  };

  const confirmSave = (e: React.MouseEvent) => {
    e.stopPropagation();
    if (!outfit.imageUrl) return;

    try {
      const savedItem = {
        id: Date.now().toString(), // Unique ID for storage
        imageUrl: outfit.imageUrl,
        name: customName, // User custom name
        description: customNotes, // User custom notes
        originalStyle: outfit.style,
        savedAt: new Date().toISOString()
      };

      const existingStorage = localStorage.getItem('styleForge_savedOutfits');
      const savedOutfits = existingStorage ? JSON.parse(existingStorage) : [];
      
      savedOutfits.push(savedItem);
      localStorage.setItem('styleForge_savedOutfits', JSON.stringify(savedOutfits));
      
      setShowSaveDialog(false);
      alert(`Saved "${customName}" to your collection!`);
    } catch (error) {
      console.error('Error saving outfit:', error);
      alert("Failed to save outfit to storage.");
    }
  };

  return (
    <div className="group relative bg-zinc-900 rounded-xl shadow-lg border border-zinc-800 overflow-hidden hover:border-zinc-600 transition-all duration-300 flex flex-col h-full">
      {/* Save Dialog Overlay */}
      {showSaveDialog && (
        <div 
            className="absolute inset-0 z-20 bg-zinc-950/95 backdrop-blur-sm p-6 flex flex-col animate-in fade-in duration-200"
            onClick={(e) => e.stopPropagation()}
        >
            <div className="flex justify-between items-center mb-6">
                <h3 className="text-lg font-serif font-bold text-white">Save Outfit</h3>
                <button 
                    onClick={(e) => { e.stopPropagation(); setShowSaveDialog(false); }}
                    className="p-1 hover:bg-zinc-800 rounded-full text-zinc-400 hover:text-white transition-colors"
                >
                    <X className="w-5 h-5" />
                </button>
            </div>

            <div className="space-y-5 flex-grow">
                <div className="space-y-2">
                    <label className="text-xs font-medium text-zinc-400 uppercase tracking-wider">Name</label>
                    <input 
                        type="text"
                        value={customName}
                        onChange={(e) => setCustomName(e.target.value)}
                        className="w-full bg-zinc-900 border border-zinc-700 rounded-lg px-4 py-3 text-white placeholder-zinc-600 focus:outline-none focus:border-white focus:ring-1 focus:ring-white transition-all"
                        placeholder="Name this look..."
                        autoFocus
                    />
                </div>
                <div className="space-y-2">
                    <label className="text-xs font-medium text-zinc-400 uppercase tracking-wider">Notes / Description</label>
                    <textarea 
                        value={customNotes}
                        onChange={(e) => setCustomNotes(e.target.value)}
                        className="w-full h-32 bg-zinc-900 border border-zinc-700 rounded-lg px-4 py-3 text-sm text-white placeholder-zinc-600 focus:outline-none focus:border-white focus:ring-1 focus:ring-white transition-all resize-none"
                        placeholder="Add notes about this outfit..."
                    />
                </div>
            </div>

            <button 
                onClick={confirmSave}
                className="w-full bg-white text-black font-bold py-3.5 rounded-xl hover:bg-zinc-200 transition-colors mt-4 shadow-lg flex items-center justify-center gap-2"
            >
                <Bookmark className="w-4 h-4 fill-current" />
                Save to Wardrobe
            </button>
        </div>
      )}

      {/* Header */}
      <div className="p-4 border-b border-white/5 flex justify-between items-center bg-zinc-900">
        <h3 className="font-serif text-lg font-bold text-white">{outfit.style}</h3>
        <div className="flex items-center gap-2">
            {outfit.imageUrl && !outfit.isLoading && (
              <>
                <button 
                    onClick={handleSaveClick}
                    className="p-1.5 text-zinc-400 hover:text-white hover:bg-zinc-800 rounded-md transition-colors"
                    title="Save Outfit"
                >
                    <Bookmark className="w-4 h-4" />
                </button>
                <button 
                    onClick={handleShare}
                    className="p-1.5 text-zinc-400 hover:text-white hover:bg-zinc-800 rounded-md transition-colors"
                    title="Share Image"
                >
                    <Share2 className="w-4 h-4" />
                </button>
              </>
            )}
            <span className="text-xs font-medium px-2 py-1 bg-black border border-zinc-700 rounded text-zinc-400 uppercase tracking-wider">
            Look {outfit.id}
            </span>
        </div>
      </div>

      {/* Image Area */}
      <div className="relative aspect-[3/4] bg-black w-full overflow-hidden">
        {outfit.isLoading ? (
          <div className="absolute inset-0 bg-zinc-950 overflow-hidden flex flex-col items-center justify-center">
             {/* Radial Gradient Background */}
             <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_50%,rgba(30,30,30,1)_0%,rgba(0,0,0,1)_100%)]" />
             
             {/* Moving Shimmer Effect */}
             <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/5 to-transparent -translate-x-full animate-shimmer" />
             
             {/* Floating Style Icon & Ring */}
             <div className="relative z-10 animate-float">
                <div className="relative p-8 rounded-full border border-white/5 bg-zinc-900/50 backdrop-blur-sm shadow-2xl group">
                    <div className="absolute inset-0 bg-white/5 blur-2xl rounded-full opacity-50" />
                    {getStyleIcon(outfit.style)}
                    
                    {/* Orbiting ring effect */}
                    <div className="absolute inset-0 border border-white/10 rounded-full animate-spin-slow border-t-white/50" />
                </div>
             </div>

             {/* Text Loading State */}
             <div className="relative z-10 mt-8 text-center space-y-3">
               <h4 className="text-white/90 font-serif text-xl tracking-wide">
                 Creating {outfit.style}
               </h4>
               <div className="flex items-center justify-center gap-2">
                 <div className="w-1 h-1 bg-zinc-500 rounded-full animate-bounce [animation-delay:-0.3s]" />
                 <div className="w-1 h-1 bg-zinc-500 rounded-full animate-bounce [animation-delay:-0.15s]" />
                 <div className="w-1 h-1 bg-zinc-500 rounded-full animate-bounce" />
               </div>
               <p className="text-xs text-zinc-600 font-medium tracking-widest uppercase">
                 AI Stylist at work
               </p>
             </div>
           </div>
        ) : outfit.imageUrl ? (
          <>
            <img 
              src={outfit.imageUrl} 
              alt={`${outfit.style} Outfit`}
              className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"
            />
            <div className="absolute inset-0 bg-black/0 group-hover:bg-black/40 transition-colors duration-300 flex items-center justify-center opacity-0 group-hover:opacity-100 cursor-pointer"
                 onClick={() => onSelect(outfit)}>
                 <button className="bg-white text-black px-6 py-2 rounded-full font-bold flex items-center gap-2 shadow-xl transform translate-y-4 group-hover:translate-y-0 transition-all hover:scale-105">
                    <Wand2 className="w-4 h-4" />
                    Edit
                 </button>
            </div>
          </>
        ) : (
           <div className="absolute inset-0 flex items-center justify-center text-zinc-600 bg-zinc-900/50">
             <span className="text-sm">Image unavailable</span>
           </div>
        )}
      </div>

      {/* Description */}
      <div className="p-5 flex-grow bg-zinc-900">
        <p className="text-sm text-zinc-300 leading-relaxed line-clamp-4">
            {outfit.description}
        </p>
      </div>
    </div>
  );
};

export default OutfitCard;